---
- name: Install packages
  apt:
    name:
      - php7.4-fpm
      # needed for roundcube
      - php7.4-mbstring
      - php7.4-xml
      - php7.4-intl
      - php7.4-zip
      - php7.4-mysql
    install_recommends: no
    purge: yes
    state: present

- name: Set permissions on /etc/php
  file:
    path: "/etc/php"
    state: directory
    mode: 0750
    owner: root
    group: root

- name: Create common pool log directory
  file:
    path: "{{ php_fpm_pools_log_dir }}"
    state: directory
    mode: 0750
    owner: root
    group: root

- name: Configure pools
  template:
    src: pools.conf.j2
    dest: "/etc/php/7.4/fpm/pool.d/pools.conf"
    owner: root
    group: root
    mode: 0644
  when: php_fpm_pools[0] is defined
  notify:
    - restart php-fpm service

- name: Enable and start service
  service:
    name: php7.4-fpm
    state: started
    enabled: yes
  when: (php_fpm_pools | length) > 0
